@testable import _D_Modeller
import Combine
import Foundation
import RealityKit
import Testing

@Suite("SceneManager Tests")
@MainActor
struct SceneManagerTests {
    // MARK: - Initialization Tests

    @Test("SceneManager initializes with root entity")
    func initialization() {
        let sceneManager = SceneManager()

        #expect(sceneManager.rootEntity != nil)
        #expect(sceneManager.entities.isEmpty)
        #expect(sceneManager.selectedEntityId == nil)
    }

    @Test("SceneManager creates grid on initialization")
    func gridCreation() {
        let sceneManager = SceneManager()

        // Root entity should have children (grid + light)
        #expect(sceneManager.rootEntity.children.count >= 2)
    }

    @Test("Initial statistics are zero")
    func initialStatistics() {
        let sceneManager = SceneManager()

        #expect(sceneManager.statistics.entityCount == 0)
        #expect(sceneManager.statistics.triangleCount == 0)
        #expect(sceneManager.statistics.materialCount == 0)
    }

    // MARK: - Primitive Creation Tests

    @Test("Create box primitive")
    func createBox() {
        let sceneManager = SceneManager()

        let entity = sceneManager.createPrimitive(type: .box, name: "TestBox")

        #expect(entity.name == "TestBox")
        #expect(entity.type == .box)
        #expect(sceneManager.entities.count == 1)
        #expect(sceneManager.statistics.entityCount == 1)
    }

    @Test("Create sphere primitive")
    func createSphere() {
        let sceneManager = SceneManager()

        let entity = sceneManager.createPrimitive(type: .sphere, name: "TestSphere")

        #expect(entity.name == "TestSphere")
        #expect(entity.type == .sphere)
    }

    @Test("Create primitive with custom position")
    func createPrimitiveWithPosition() {
        let sceneManager = SceneManager()
        let position: SIMD3<Float> = [1.0, 2.0, 3.0]

        let entity = sceneManager.createPrimitive(type: .box, position: position)

        #expect(entity.entity.position == position)
    }

    @Test("Create primitive with custom color")
    func createPrimitiveWithColor() {
        let sceneManager = SceneManager()
        let color = ColorData(r: 1.0, g: 0.0, b: 0.0)

        let entity = sceneManager.createPrimitive(type: .box, color: color)

        #expect(entity.material.color.r == 1.0)
        #expect(entity.material.color.g == 0.0)
        #expect(entity.material.color.b == 0.0)
    }

    @Test("Auto-generated names increment")
    func autoGeneratedNames() {
        let sceneManager = SceneManager()

        let box1 = sceneManager.createPrimitive(type: .box)
        let box2 = sceneManager.createPrimitive(type: .box)
        let sphere1 = sceneManager.createPrimitive(type: .sphere)

        #expect(box1.name == "Box_1")
        #expect(box2.name == "Box_2")
        #expect(sphere1.name == "Sphere_1")
    }

    // MARK: - Delete Tests

    @Test("Delete entity by ID")
    func deleteEntityById() {
        let sceneManager = SceneManager()
        let entity = sceneManager.createPrimitive(type: .box)

        let result = sceneManager.deleteEntity(id: entity.id)

        #expect(result == true)
        #expect(sceneManager.entities.isEmpty)
        #expect(sceneManager.statistics.entityCount == 0)
    }

    @Test("Delete entity by name")
    func deleteEntityByName() {
        let sceneManager = SceneManager()
        _ = sceneManager.createPrimitive(type: .box, name: "ToDelete")

        let result = sceneManager.deleteEntity(named: "ToDelete")

        #expect(result == true)
        #expect(sceneManager.entities.isEmpty)
    }

    @Test("Delete non-existent entity returns false")
    func deleteNonExistentEntity() {
        let sceneManager = SceneManager()

        let result = sceneManager.deleteEntity(id: UUID())

        #expect(result == false)
    }

    @Test("Delete clears selection if selected")
    func deleteClearsSelection() {
        let sceneManager = SceneManager()
        let entity = sceneManager.createPrimitive(type: .box)
        sceneManager.select(id: entity.id)

        _ = sceneManager.deleteEntity(id: entity.id)

        #expect(sceneManager.selectedEntityId == nil)
    }

    // MARK: - Transform Tests

    @Test("Transform entity position")
    func transformPosition() {
        let sceneManager = SceneManager()
        let entity = sceneManager.createPrimitive(type: .box)
        let newPosition: SIMD3<Float> = [5.0, 5.0, 5.0]

        let result = sceneManager.transformEntity(id: entity.id, position: newPosition)

        #expect(result == true)
        #expect(entity.entity.position == newPosition)
    }

    @Test("Transform entity scale")
    func transformScale() {
        let sceneManager = SceneManager()
        let entity = sceneManager.createPrimitive(type: .box)
        let newScale: SIMD3<Float> = [2.0, 2.0, 2.0]

        let result = sceneManager.transformEntity(id: entity.id, scale: newScale)

        #expect(result == true)
        #expect(entity.entity.scale == newScale)
    }

    @Test("Transform by name")
    func transformByName() {
        let sceneManager = SceneManager()
        _ = sceneManager.createPrimitive(type: .box, name: "Movable")
        let newPosition: SIMD3<Float> = [10.0, 0.0, 0.0]

        let result = sceneManager.transformEntity(named: "Movable", position: newPosition)

        #expect(result == true)
        #expect(sceneManager.entity(named: "Movable")?.entity.position == newPosition)
    }

    // MARK: - Material Tests

    @Test("Set material color")
    func setMaterialColor() {
        let sceneManager = SceneManager()
        let entity = sceneManager.createPrimitive(type: .box)
        let newColor = ColorData(r: 0.0, g: 1.0, b: 0.0)

        let result = sceneManager.setMaterial(id: entity.id, color: newColor)

        #expect(result == true)
        #expect(entity.material.color.g == 1.0)
    }

    @Test("Set material metallic")
    func setMaterialMetallic() {
        let sceneManager = SceneManager()
        let entity = sceneManager.createPrimitive(type: .box)

        let result = sceneManager.setMaterial(id: entity.id, metallic: 0.8)

        #expect(result == true)
        #expect(entity.material.metallic == 0.8)
    }

    // MARK: - Change Notification Tests

    @Test("Transforming an entity publishes a change")
    func transformPublishesChange() {
        let sceneManager = SceneManager()
        let entity = sceneManager.createPrimitive(type: .box)
        var changes = 0
        let subscription = sceneManager.objectWillChange.sink { changes += 1 }

        _ = sceneManager.transformEntity(id: entity.id, position: [0, 1, 0])

        #expect(changes > 0)
        subscription.cancel()
    }

    @Test("Changing a material publishes a change")
    func setMaterialPublishesChange() {
        let sceneManager = SceneManager()
        let entity = sceneManager.createPrimitive(type: .box)
        var changes = 0
        let subscription = sceneManager.objectWillChange.sink { changes += 1 }

        _ = sceneManager.setMaterial(id: entity.id, metallic: 1.0)

        #expect(changes > 0)
        subscription.cancel()
    }

    @Test("Every scene edit bumps the revision")
    func revisionBumpsOnEdits() {
        let sceneManager = SceneManager()
        let start = sceneManager.revision

        let entity = sceneManager.createPrimitive(type: .box)
        let afterCreate = sceneManager.revision
        _ = sceneManager.transformEntity(id: entity.id, position: [0, 1, 0])
        let afterTransform = sceneManager.revision
        _ = sceneManager.setMaterial(id: entity.id, roughness: 0.2)
        let afterMaterial = sceneManager.revision
        _ = sceneManager.deleteEntity(id: entity.id)

        #expect(afterCreate > start)
        #expect(afterTransform > afterCreate)
        #expect(afterMaterial > afterTransform)
        #expect(sceneManager.revision > afterMaterial)
    }

    // MARK: - Selection Tests

    @Test("Select entity by ID")
    func selectById() {
        let sceneManager = SceneManager()
        let entity = sceneManager.createPrimitive(type: .box)

        sceneManager.select(id: entity.id)

        #expect(sceneManager.selectedEntityId == entity.id)
        #expect(sceneManager.selectedEntity?.id == entity.id)
    }

    @Test("Select entity by name")
    func selectByName() {
        let sceneManager = SceneManager()
        let entity = sceneManager.createPrimitive(type: .box, name: "Selectable")

        sceneManager.select(named: "Selectable")

        #expect(sceneManager.selectedEntityId == entity.id)
    }

    @Test("Deselect by passing nil")
    func deselect() {
        let sceneManager = SceneManager()
        let entity = sceneManager.createPrimitive(type: .box)
        sceneManager.select(id: entity.id)

        sceneManager.select(id: nil)

        #expect(sceneManager.selectedEntityId == nil)
    }

    // MARK: - Duplicate Tests

    @Test("Duplicate entity")
    func testDuplicateEntity() {
        let sceneManager = SceneManager()
        let original = sceneManager.createPrimitive(type: .sphere, name: "Original")

        let duplicate = sceneManager.duplicateEntity(id: original.id)

        #expect(duplicate != nil)
        #expect(duplicate?.name == "Original_copy")
        #expect(duplicate?.type == .sphere)
        #expect(sceneManager.entities.count == 2)
    }

    @Test("Duplicate with custom name")
    func duplicateWithCustomName() {
        let sceneManager = SceneManager()
        let original = sceneManager.createPrimitive(type: .box)

        let duplicate = sceneManager.duplicateEntity(id: original.id, newName: "CustomCopy")

        #expect(duplicate?.name == "CustomCopy")
    }

    // MARK: - Serialization Tests

    @Test("Serialize empty scene")
    func serializeEmptyScene() {
        let sceneManager = SceneManager()

        let data = sceneManager.toSceneData()

        #expect(data.entities.isEmpty)
    }

    @Test("Serialize scene with entities")
    func serializeWithEntities() {
        let sceneManager = SceneManager()
        _ = sceneManager.createPrimitive(type: .box, name: "Box1")
        _ = sceneManager.createPrimitive(type: .sphere, name: "Sphere1")

        let data = sceneManager.toSceneData()

        #expect(data.entities.count == 2)
    }

    @Test("Load scene data")
    func testLoadSceneData() {
        let sceneManager = SceneManager()

        var sceneData = SceneData()
        sceneData.entities = [
            EntityData(name: "LoadedBox", type: .box),
            EntityData(name: "LoadedSphere", type: .sphere),
        ]

        sceneManager.loadSceneData(sceneData)

        #expect(sceneManager.entities.count == 2)
        #expect(sceneManager.entity(named: "LoadedBox") != nil)
        #expect(sceneManager.entity(named: "LoadedSphere") != nil)
    }

    @Test("Load clears existing entities")
    func loadClearsExisting() {
        let sceneManager = SceneManager()
        _ = sceneManager.createPrimitive(type: .box, name: "Existing")

        var sceneData = SceneData()
        sceneData.entities = [EntityData(name: "New", type: .sphere)]

        sceneManager.loadSceneData(sceneData)

        #expect(sceneManager.entities.count == 1)
        #expect(sceneManager.entity(named: "Existing") == nil)
        #expect(sceneManager.entity(named: "New") != nil)
    }

    // MARK: - Round-Trip Tests

    private func isClose(_ a: SIMD3<Float>, _ b: SIMD3<Float>, tolerance: Float = 1e-4) -> Bool {
        simd_length(a - b) < tolerance
    }

    private func sampleSceneData() -> SceneData {
        var data = SceneData()
        data.metadata.name = "My Workshop"
        data.metadata.createdAt = Date(timeIntervalSince1970: 1_000_000)
        data.entities = [
            EntityData(
                id: UUID(),
                name: "Table",
                type: .box,
                transform: TransformData(
                    position: [1, 2, 3],
                    rotation: [0.3, -0.5, 1.1],
                    scale: [2, 0.5, 1.5]
                ),
                material: MaterialData(
                    color: ColorData(r: 0.1, g: 0.2, b: 0.3, a: 0.9),
                    metallic: 0.7,
                    roughness: 0.25
                ),
                parentId: UUID(),
                isVisible: false
            )
        ]
        return data
    }

    @Test("Save after load keeps every entity field")
    func entityRoundTrip() throws {
        let sceneManager = SceneManager()
        let original = sampleSceneData()

        sceneManager.loadSceneData(original)
        let saved = try #require(sceneManager.toSceneData().entities.first)
        let expected = original.entities[0]

        #expect(saved.id == expected.id)
        #expect(saved.name == expected.name)
        #expect(saved.type == expected.type)
        #expect(isClose(saved.transform.position, expected.transform.position))
        #expect(isClose(saved.transform.rotation, expected.transform.rotation))
        #expect(isClose(saved.transform.scale, expected.transform.scale))
        #expect(saved.material.color == expected.material.color)
        #expect(saved.material.metallic == expected.material.metallic)
        #expect(saved.material.roughness == expected.material.roughness)
        #expect(saved.parentId == expected.parentId)
        #expect(saved.isVisible == expected.isVisible)
    }

    @Test("Save after load keeps the scene metadata")
    func metadataRoundTrip() {
        let sceneManager = SceneManager()
        let original = sampleSceneData()

        sceneManager.loadSceneData(original)
        _ = sceneManager.transformEntity(id: original.entities[0].id, position: [0, 0, 0])
        let saved = sceneManager.toSceneData()

        #expect(saved.metadata.name == "My Workshop")
        #expect(saved.metadata.createdAt == original.metadata.createdAt)
    }

    @Test("Rotation set in degrees is saved in radians")
    func rotationSerialization() throws {
        let sceneManager = SceneManager()
        let entity = sceneManager.createPrimitive(type: .box)

        _ = sceneManager.transformEntity(id: entity.id, rotation: [30, 45, 60])
        let saved = try #require(sceneManager.toSceneData().entities.first)

        #expect(isClose(saved.transform.rotation, SIMD3<Float>(30, 45, 60) * (.pi / 180)))
    }

    @Test("Loading a scene does not count as an edit")
    func loadDoesNotTouchUndoOrRevision() {
        let sceneManager = SceneManager()
        let revision = sceneManager.revision

        sceneManager.loadSceneData(sampleSceneData())
        sceneManager.undo()

        #expect(sceneManager.revision == revision)
        #expect(sceneManager.entities.count == 1)
        #expect(sceneManager.statistics.entityCount == 1)
    }

    @Test("Undo restores the previous transform")
    func undoRestoresTransform() {
        let sceneManager = SceneManager()
        let entity = sceneManager.createPrimitive(type: .box, position: [1, 0, 0])

        _ = sceneManager.transformEntity(id: entity.id, position: [5, 5, 5], scale: [2, 2, 2])
        sceneManager.undo()

        let restored = sceneManager.entities[entity.id]
        #expect(restored?.entity.position == [1, 0, 0])
        #expect(restored?.entity.scale == [1, 1, 1])
    }

    @Test("Undo then redo returns to the edited state")
    func undoThenRedo() throws {
        let sceneManager = SceneManager()
        let original = sampleSceneData()
        sceneManager.loadSceneData(original)
        let id = original.entities[0].id
        let loaded = try #require(sceneManager.toSceneData().entities.first)

        _ = sceneManager.setMaterial(id: id, metallic: 0.1)
        _ = sceneManager.transformEntity(id: id, scale: [3, 3, 3])
        let edited = try #require(sceneManager.toSceneData().entities.first)

        sceneManager.undo()
        sceneManager.undo()
        let undone = try #require(sceneManager.toSceneData().entities.first)
        #expect(undone.id == loaded.id)
        #expect(undone.material.metallic == loaded.material.metallic)
        #expect(isClose(undone.transform.scale, loaded.transform.scale))
        #expect(isClose(undone.transform.rotation, loaded.transform.rotation))

        sceneManager.redo()
        sceneManager.redo()
        let redone = try #require(sceneManager.toSceneData().entities.first)
        #expect(redone.id == edited.id)
        #expect(redone.material.metallic == 0.1)
        #expect(isClose(redone.transform.scale, [3, 3, 3]))
        #expect(isClose(redone.transform.rotation, loaded.transform.rotation))
        #expect(redone.isVisible == false)
    }

    @Test("Undo does not clear the redo stack")
    func undoKeepsRedoStack() {
        let sceneManager = SceneManager()
        _ = sceneManager.createPrimitive(type: .box, name: "A")
        _ = sceneManager.createPrimitive(type: .box, name: "B")

        sceneManager.undo()
        sceneManager.undo()
        sceneManager.redo()
        sceneManager.redo()

        #expect(sceneManager.entity(named: "A") != nil)
        #expect(sceneManager.entity(named: "B") != nil)
        sceneManager.undo()
        #expect(sceneManager.entity(named: "B") == nil)
    }

    @Test("Loading a document is not an edit")
    func loadDoesNotBumpRevision() {
        let sceneManager = SceneManager()
        var sceneData = SceneData()
        sceneData.entities = [EntityData(name: "LoadedBox", type: .box)]
        let start = sceneManager.revision

        sceneManager.loadSceneData(sceneData)

        #expect(sceneManager.revision == start)
        #expect(sceneManager.statistics.entityCount == 1)
    }

    @Test("Undo right after loading keeps the loaded objects")
    func loadStartsWithEmptyUndoHistory() {
        let sceneManager = SceneManager()
        var sceneData = SceneData()
        sceneData.entities = [EntityData(name: "LoadedBox", type: .box)]
        sceneManager.loadSceneData(sceneData)

        sceneManager.undo()

        #expect(sceneManager.entity(named: "LoadedBox") != nil)
    }

    // MARK: - Undo/Redo Tests

    @Test("Undoing a delete restores exactly one entity with the original id")
    func undoDeleteRestoresOriginalEntity() {
        let sceneManager = SceneManager()
        let entity = sceneManager.createPrimitive(type: .box, name: "Keeper")
        _ = sceneManager.deleteEntity(id: entity.id)

        sceneManager.undo()

        #expect(sceneManager.entities.count == 1)
        #expect(sceneManager.entities[entity.id]?.name == "Keeper")
        #expect(sceneManager.statistics.entityCount == 1)
    }

    @Test("Undo then redo walks the history in both directions")
    func testUndoThenRedo() {
        let sceneManager = SceneManager()
        let first = sceneManager.createPrimitive(type: .box, name: "First")
        let second = sceneManager.createPrimitive(type: .sphere, name: "Second")

        sceneManager.undo()
        sceneManager.undo()
        #expect(sceneManager.entities.isEmpty)

        sceneManager.redo()
        #expect(Set(sceneManager.entities.keys) == [first.id])

        sceneManager.redo()
        #expect(Set(sceneManager.entities.keys) == [first.id, second.id])
    }

    @Test("Material, rotation and scale survive undo")
    func undoKeepsMaterialAndTransform() throws {
        let sceneManager = SceneManager()
        let entity = sceneManager.createPrimitive(type: .box)
        _ = sceneManager.setMaterial(
            id: entity.id, color: ColorData(r: 0, g: 0, b: 1), metallic: 0.8, roughness: 0.2
        )
        _ = sceneManager.transformEntity(id: entity.id, rotation: [0, 90, 0], scale: [2, 2, 2])
        let orientation = entity.entity.orientation
        _ = sceneManager.deleteEntity(id: entity.id)

        sceneManager.undo()

        let restored = try #require(sceneManager.entities[entity.id])
        #expect(restored.material.color == ColorData(r: 0, g: 0, b: 1))
        #expect(restored.material.metallic == 0.8)
        #expect(restored.material.roughness == 0.2)
        #expect(restored.entity.scale == [2, 2, 2])
        #expect(restored.entity.orientation == orientation)
        #expect(restored.entity.parent === sceneManager.rootEntity)
    }

    @Test("Undoing a transform puts the entity back where it was")
    func undoTransform() throws {
        let sceneManager = SceneManager()
        let entity = sceneManager.createPrimitive(type: .box, position: [1, 0, 0])
        _ = sceneManager.transformEntity(id: entity.id, position: [5, 5, 5])

        sceneManager.undo()

        let restored = try #require(sceneManager.entities[entity.id])
        #expect(restored.entity.position == [1, 0, 0])
    }

    @Test("Undo keeps the mesh size of a custom-sized primitive")
    func undoKeepsMeshSize() {
        let sceneManager = SceneManager()
        let entity = sceneManager.createPrimitive(type: .box, size: 2)

        _ = sceneManager.transformEntity(id: entity.id, position: [1, 0, 0])
        sceneManager.undo()

        let extents = sceneManager.entities[entity.id]?.entity.visualBounds(relativeTo: nil).extents
        #expect(extents.map { isClose($0, [2, 2, 2]) } == true)
    }

    // MARK: - Entity Lookup Tests

    @Test("Find entity by name")
    func findEntityByName() {
        let sceneManager = SceneManager()
        let created = sceneManager.createPrimitive(type: .cone, name: "FindMe")

        let found = sceneManager.entity(named: "FindMe")

        #expect(found?.id == created.id)
    }

    @Test("Find non-existent entity returns nil")
    func findNonExistentEntity() {
        let sceneManager = SceneManager()

        let found = sceneManager.entity(named: "DoesNotExist")

        #expect(found == nil)
    }
}
